import type { Metadata, NextPage } from 'next';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import './styles.scss';
import { ReactNode } from 'react';
import { languages } from '../i18n/settings';
import Navbar from './components/shared/Navbar';
import Footer from './components/shared/Footer';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: ReactNode;
  params: {
    lng: string;
  };
}

const RootLayout: NextPage<RootLayoutProps> = ({
  children,
  params: { lng },
}) => {
  return (
    <html lang={lng}>
      <body className={inter.className}>
        <Navbar lng={lng} />
        {children}
        <Footer lng={lng} />
      </body>
    </html>
  );
};

export default RootLayout;
